workflows:
  flutter-apk-workflow:
    name: APK Yemen Market (TEMP SHELL)
    max_build_duration: 60

    environment:
      flutter: stable

    scripts:
      - name: إنشاء Flutter App مؤقت
        script: |
          flutter create temp_app
          rm -rf temp_app/lib
          cp -r lib temp_app/
          cp pubspec.yaml temp_app/
          cp -r assets temp_app/ || true
          cd temp_app
          flutter pub get

      - name: بناء APK Release
        script: |
          cd temp_app
          flutter build apk --release --no-tree-shake-icons

    artifacts:
      - temp_app/build/app/outputs/flutter-apk/app-release.apk
